server:
  port: 9191

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: CART-SERVICE
          uri: lb://CART-SERVICE/**
          predicates:
            - Path=/api/cart
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE/**
          predicates:
            - Path=/api/order

#  loadbalance = lbY


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discoveryservice-webshop.azurewebsites.net/
  instance:
    hostname:  azurewebsites.net